# Generated by Django 3.0.8 on 2020-07-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your real name', max_length=50)),
                ('display_name', models.CharField(help_text='Enter your preferred display name', max_length=50)),
                ('email', models.EmailField(help_text='Enter your email address', max_length=254)),
                ('about', models.CharField(help_text='Provide a little bit of detail about yourself', max_length=1000)),
                ('spoken_languages', models.CharField(help_text='List the languages you speak including proficiency level', max_length=200)),
                ('github', models.URLField(help_text='Provide a link to your GitHub page')),
                ('linkedin', models.URLField(help_text='Provide a link to your LinkedIn page')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('profiles', models.ManyToManyField(to='profiles.Profile')),
            ],
            options={
                'ordering': ['category', 'skill'],
            },
        ),
    ]
