# Generated by Django 3.0.8 on 2020-07-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='profiles',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(help_text='Select skills for this profile', to='profiles.Skills'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Enter your preferred display name', max_length=50),
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('company_alias', models.CharField(blank=True, help_text='If you do not want to display company name, provide an alias description', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('job_title', models.CharField(max_length=100)),
                ('duties', models.CharField(max_length=1500)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('duties', models.CharField(max_length=1500)),
                ('programming_languages', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'ordering': ['project_title'],
            },
        ),
    ]
