# Generated by Django 3.0.8 on 2020-07-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200703_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, help_text='Provide a link to your GitHub page'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Provide a link to your LinkedIn page'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spoken_languages',
            field=models.CharField(blank=True, help_text='List the languages you speak including proficiency level', max_length=200),
        ),
    ]
